### ISSUE TITLE
plcprog-console builds may not find database correctly for load_plc_databases.cmd

### ISSUE THREAD

**Issue by klauer** [pcdshub/ads-deploy#36]
## Current Behavior
The database is built correctly but the additional `.cmd` file is not.

```
Traceback (most recent call last):
  File "c:/Repos/ads-ioc/R0.5.0//iocBoot/templates/dbloads.py", line 63, in <module>
    main()
  File "c:/Repos/ads-ioc/R0.5.0//iocBoot/templates/dbloads.py", line 46, in main
    total_records = sum(count_number_of_records(fn) for fn in db_filenames)
  File "c:/Repos/ads-ioc/R0.5.0//iocBoot/templates/dbloads.py", line 46, in <genexpr>
    total_records = sum(count_number_of_records(fn) for fn in db_filenames)
  File "c:/Repos/ads-ioc/R0.5.0//iocBoot/templates/dbloads.py", line 23, in count_number_of_records
    with open(db_filename, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/c/Users/klauer/Documents/Repos/lcls-plc-las-bts/iocBoot/ioc-las-bts/.pytmc_build/las_bts.db'
* Installing: las_bts.db
```

Need to dig into details here.

Can always rebuild on linux, of course, so it's not a show-stopper.

**Comment by klauer** [comment]
This has to do with the cygwin/posix-style paths not being translated when running `dbloads.py`
