### ISSUE TITLE
Attempted pytmc project summary

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/ads-deploy#6]
```DisplayStats.sLine1 := 'PMPS-ARBITER-K';
fbFormat(sFormat := 'Fast Faults: %d', arg1:=F_ULINT(PMPS_GVL.AccumulatedFF), sOut=>DisplayStats.sLine2, bError => bError, nErrID => nErrID ); 

DisplayStats(eMode:=E_CX2100_DisplayModesWr.eCX2100_WriteLines);


Traceback (most recent call last):
  File "/usr/local/bin/pytmc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pytmc/bin/pytmc.py", line 83, in main
    func(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytmc/bin/summary.py", line 236, in main
    log_level=log_level, debug=debug
  File "/usr/local/lib/python3.7/site-packages/pytmc/bin/summary.py", line 143, in summary
    if not decl_or_impl.text.strip():
AttributeError: 'NoneType' object has no attribute 'strip'```

**Comment by klauer** [comment]
Looks like an empty declaration/implementation section in one of your source code files. I'll fix it in `pytmc`. Is the project up-to-date on github so I can verify the fix @slacAWallace?

**Comment by slacAWallace** [comment]
[Latest](https://github.com/slacAWallace/pmps-dev-arbiter)
